header_format = '4s2L' # 12 bytes
header_length = 12
vertex_header = 'L' # 4 bytes
vheader_length = 4
vertex_format = '8f4B4f' # 52 bytes
vertex_length = 52
face_header = 'L' # 4 bytes
fheader_length = 4
face_format = '3H' # 6 bytes
face_length = 6
bone_header = 'L' # 4 bytes
bheader_length = 4
bone_format = '7f' # 28 bytes
bone_length = 28
numPropPoint_header = 'L' # 4 bytes
pheader_length = 4
propPointName_header = 'L' # 4 bytes
pName_header_length = 4
propPointName_format = 'c' # 1 byte, variable length, based on propPointName_header
pName_length = 1
propPoint_format = '7f1B' # 29 bytes
propPoint_length = 29
